### ISSUE TITLE
AppStore Upload Error: Invalid Bundle Structure

### ISSUE THREAD

**Issue by 1agora** [kewlbear/Open3D-iOS#11]
Multiple errors like below (on each .a file) on uploading to the AppStore:

`ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'MyApp.app/NumPy-iOS_NumPySupport.bundle/site-packages/numpy/core/lib/libnpymath.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."`

**Comment by kewlbear** [comment]
Updated NumPy-iOS with fix. Successfully uploaded test app with Xcode 12.5 beta 3. Please update the package to see if it works for you.

**Comment by acamill** [comment]
Gamsamnida @kewlbear

**Comment by kewlbear** [comment]
Actually there are some private API usage issues regarding BLAS and LAPACK. I'm working on it.

**Comment by kewlbear** [comment]
> Actually there are some private API usage issues regarding BLAS and LAPACK. I'm working on it.

Done.

**Comment by 1agora** [comment]
big thanks for your efforts and quick responses!

i am still getting same bunch of errors (nothing about private API's). 
Open3D-iOS is embedded into another project and updated to latest.

![image](https://user-images.githubusercontent.com/704565/114665689-ec650800-9d2f-11eb-9a08-5600f3dc171e.png)

when archiving Example App:

![image](https://user-images.githubusercontent.com/704565/114665531-bd4e9680-9d2f-11eb-9f65-ae7ebd5d8ba2.png)

**Comment by kewlbear** [comment]
Use Xcode 12.5 beta 3. It does a lot for you.

**Comment by 1agora** [comment]
Xcode version was not the reason for the errors in my case. Now using Xcode 12.5 beta3:

Example.app build seems to error out on Release builds only.

for simulator: SUCCESS
for actual connected device: SUCCESS
for any iOS device (arm64): FAIL (Error: No matching function for call to 'lsamen_'.) 
      along with (Command CompileSwift failed with a nonzero exit code) and 
                         (NumpySupport: Command SwiftCodeGeneration failed with a nonzero exit code)

Archive (release): fail with same above errors. 
Archive (debug): SUCCESS + uploaded to appstore - crashes on launch:

```
Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x000000019e02eaa8
Termination Signal: Trace/BPT trap: 5
Termination Reason: Namespace SIGNAL, Code 0x5
Terminating Process: exc handler [6863]
Triggered by Thread:  0

Thread 0 name:
Thread 0 Crashed:
0   libswiftCore.dylib            	0x000000019e02eaa8 _assertionFailure(_:_:file:line:flags:) + 488 (AssertCommon.swift:132)
1   libswiftCore.dylib            	0x000000019e02eaa8 _assertionFailure(_:_:file:line:flags:) + 488 (AssertCommon.swift:132)
2   TrueDepthScanning             	0x0000000100a384b8 0x100968000 + 853176
3   TrueDepthScanning             	0x0000000100a382b8 0x100968000 + 852664
4   libdispatch.dylib             	0x000000019a242280 _dispatch_client_callout + 16 (object.m:559)
5   libdispatch.dylib             	0x000000019a213cd8 _dispatch_once_callout + 28 (once.c:52)
6   libswiftCore.dylib            	0x000000019e31bd68 swift_once + 44 (once.h:111)
7   TrueDepthScanning             	0x0000000100a38748 0x100968000 + 853832
8   TrueDepthScanning             	0x0000000100a39170 static PythonLibrary.loadSymbol<A>(name:legacyName:type:) + 580 (PythonLibrary.swift:70)
9   TrueDepthScanning             	0x0000000100a34bbc 0x100968000 + 838588
10  libdispatch.dylib             	0x000000019a242280 _dispatch_client_callout + 16 (object.m:559)
11  libdispatch.dylib             	0x000000019a213cd8 _dispatch_once_callout + 28 (once.c:52)
12  libswiftCore.dylib            	0x000000019e31bd68 swift_once + 44 (once.h:111)
13  TrueDepthScanning             	0x0000000100a34c18 0x100968000 + 838680
14  TrueDepthScanning             	0x0000000100a263b8 PythonInterface.init() + 28 (Python.swift:646)
15  TrueDepthScanning             	0x0000000100a26388 one-time initialization function for Python + 12 (Python.swift:631)
16  libdispatch.dylib             	0x000000019a242280 _dispatch_client_callout + 16 (object.m:559)
17  libdispatch.dylib             	0x000000019a213cd8 _dispatch_once_callout + 28 (once.c:52)
18  libswiftCore.dylib            	0x000000019e31bd68 swift_once + 44 (once.h:111)
19  TrueDepthScanning             	0x0000000100a2092c Python.unsafeMutableAddressor + 64 (Python.swift:631)
20  TrueDepthScanning             	0x000000010097b67c Open3D.init() + 1000 (Open3D.swift:77)
```
